#
# Makefile for implementations of primality testing and
# factorization methods in C
#
# Math 371 Number Theory Spring 2016
# Rochester Institute of Technology
#
# Author(s): Margaret Dorsey, Jodie Miu
#


all:


# Fermat Test

######### Simple Version

######### Big Data Version

######### Parallel Big Data Version


# Strong Test

